# SPDX-License-Identifier: LicenseRef-Rateslib-Dual
#
# Copyright (c) 2026 Siffrorna Technology Limited
#
# Dual-licensed: Free Educational Licence or Paid Commercial Licence (commercial/professional use)
# Source-available, not open source.
#
# See LICENSE and https://rateslib.com/py/en/latest/i_licence.html for details,
# and/or contact info (at) rateslib (dot) com
####################################################################################################

from __future__ import annotations

import os
from typing import TYPE_CHECKING

import pandas as pd
from packaging import version

if TYPE_CHECKING:
    from rateslib.local_types import (  # pragma: no cover
        Any,
    )


# This is output from a development version and hard coded before a release for performance.
INSTRUMENT_SPECS = {
    "test": {
        "frequency": "m",
        "stub": "longfront",
        "eom": False,
        "modifier": "p",
        "calendar": "nyc,tgt,ldn",
        "payment_lag": 4,
        "currency": "tes",
        "convention": "yearsmonths",
        "leg2_frequency": "m",
        "leg2_stub": "longback",
        "leg2_roll": 1,
        "leg2_eom": False,
        "leg2_modifier": "mp",
        "leg2_calendar": "nyc,tgt,ldn",
        "leg2_payment_lag": 3,
        "leg2_convention": "one",
    },
    "eurusd_call": {
        "modifier": "mf",
        "calendar": "tgt|fed",
        "payment_lag": 2,
        "pair": "eurusd",
        "delivery_lag": 2,
    },
    "us_ig_cds": {
        "frequency": "q",
        "stub": "shortfront",
        "roll": 20,
        "eom": False,
        "modifier": "fex",
        "calendar": "nyc",
        "payment_lag": 0,
        "currency": "usd",
        "convention": "act360",
        "fixed_rate": 1.0,
    },
    "inr_ndirs": {
        "frequency": "s",
        "stub": "shortfront",
        "eom": False,
        "modifier": "mf",
        "calendar": "mum",
        "payment_lag": 0,
        "currency": "usd",
        "convention": "act365f",
        "pair": "usdinr",
        "leg2_spread_compound_method": "none_simple",
        "leg2_fixing_method": "rfr_payment_delay",
    },
    "inrusd_ndxcs": {
        "frequency": "s",
        "stub": "shortfront",
        "eom": False,
        "modifier": "mf",
        "calendar": "mum|fed",
        "payment_lag": 2,
        "currency": "usd",
        "convention": "act365f",
        "fixed": True,
        "pair": "usdinr",
        "leg2_convention": "act360",
        "leg2_spread_compound_method": "none_simple",
        "leg2_fixing_method": "rfr_payment_delay",
    },
    "mxn_irs": {
        "frequency": "28d",
        "stub": "shortfront",
        "eom": False,
        "modifier": "f",
        "calendar": "mex",
        "payment_lag": 2,
        "currency": "mxn",
        "convention": "act360",
        "leg2_spread_compound_method": "none_simple",
        "leg2_fixing_method": "rfr_payment_delay",
    },
    "usd_irs": {
        "frequency": "a",
        "stub": "shortfront",
        "eom": False,
        "modifier": "mf",
        "calendar": "nyc",
        "payment_lag": 2,
        "currency": "usd",
        "convention": "act360",
        "leg2_spread_compound_method": "none_simple",
        "leg2_fixing_method": "rfr_payment_delay",
    },
    "usd_irs_lt_2y": {
        "frequency": "a",
        "stub": "shortfront",
        "eom": True,
        "modifier": "mf",
        "calendar": "nyc",
        "payment_lag": 2,
        "currency": "usd",
        "convention": "act360",
        "leg2_spread_compound_method": "none_simple",
        "leg2_fixing_method": "rfr_payment_delay",
    },
    "gbp_irs": {
        "frequency": "a",
        "stub": "shortfront",
        "eom": True,
        "modifier": "mf",
        "calendar": "ldn",
        "payment_lag": 0,
        "currency": "gbp",
        "convention": "act365f",
        "leg2_spread_compound_method": "none_simple",
        "leg2_fixing_method": "rfr_payment_delay",
    },
    "eur_irs": {
        "frequency": "a",
        "stub": "shortfront",
        "eom": False,
        "modifier": "mf",
        "calendar": "tgt",
        "payment_lag": 1,
        "currency": "eur",
        "convention": "act360",
        "leg2_spread_compound_method": "none_simple",
        "leg2_fixing_method": "rfr_payment_delay",
    },
    "sek_irs": {
        "frequency": "a",
        "stub": "shortfront",
        "eom": False,
        "modifier": "mf",
        "calendar": "stk",
        "payment_lag": 1,
        "currency": "sek",
        "convention": "act360",
        "leg2_spread_compound_method": "none_simple",
        "leg2_fixing_method": "rfr_payment_delay",
    },
    "nok_irs": {
        "frequency": "a",
        "stub": "shortfront",
        "eom": False,
        "modifier": "mf",
        "calendar": "osl",
        "payment_lag": 2,
        "currency": "nok",
        "convention": "act365f",
        "leg2_spread_compound_method": "none_simple",
        "leg2_fixing_method": "rfr_payment_delay",
    },
    "chf_irs": {
        "frequency": "a",
        "stub": "shortfront",
        "eom": False,
        "modifier": "mf",
        "calendar": "zur",
        "payment_lag": 2,
        "currency": "chf",
        "convention": "act360",
        "leg2_spread_compound_method": "none_simple",
        "leg2_fixing_method": "rfr_payment_delay",
    },
    "cad_irs": {
        "frequency": "s",
        "stub": "shortfront",
        "eom": False,
        "modifier": "mf",
        "calendar": "tro",
        "payment_lag": 1,
        "currency": "cad",
        "convention": "act365f",
        "leg2_spread_compound_method": "none_simple",
        "leg2_fixing_method": "rfr_payment_delay",
    },
    "cad_irs_le_1y": {
        "frequency": "a",
        "stub": "shortfront",
        "eom": True,
        "modifier": "mf",
        "calendar": "tro",
        "payment_lag": 1,
        "currency": "cad",
        "convention": "act365f",
        "leg2_spread_compound_method": "none_simple",
        "leg2_fixing_method": "rfr_payment_delay",
    },
    "jpy_irs": {
        "frequency": "a",
        "stub": "shortfront",
        "eom": True,
        "modifier": "mf",
        "calendar": "tyo",
        "payment_lag": 2,
        "currency": "jpy",
        "convention": "act365f",
        "leg2_spread_compound_method": "none_simple",
        "leg2_fixing_method": "rfr_payment_delay",
    },
    "nzd_irs3": {
        "frequency": "s",
        "stub": "shortfront",
        "eom": True,
        "modifier": "mf",
        "calendar": "wlg",
        "payment_lag": 0,
        "currency": "nzd",
        "convention": "act365f",
        "leg2_frequency": "q",
        "leg2_spread_compound_method": "none_simple",
        "leg2_fixing_method": "ibor(0)",
    },
    "nzd_irs6": {
        "frequency": "s",
        "stub": "shortfront",
        "eom": True,
        "modifier": "mf",
        "calendar": "wlg",
        "payment_lag": 0,
        "currency": "nzd",
        "convention": "act365f",
        "leg2_spread_compound_method": "none_simple",
        "leg2_fixing_method": "ibor(0)",
    },
    "nzd_irs": {
        "frequency": "a",
        "stub": "shortfront",
        "eom": True,
        "modifier": "mf",
        "calendar": "wlg",
        "payment_lag": 2,
        "currency": "nzd",
        "convention": "act365f",
        "leg2_spread_compound_method": "none_simple",
        "leg2_fixing_method": "rfr_payment_delay",
    },
    "aud_irs6": {
        "frequency": "s",
        "stub": "shortfront",
        "eom": True,
        "modifier": "mf",
        "calendar": "syd",
        "payment_lag": 0,
        "currency": "aud",
        "convention": "act365f",
        "leg2_spread_compound_method": "none_simple",
        "leg2_fixing_method": "ibor(0)",
    },
    "aud_irs3": {
        "frequency": "q",
        "stub": "shortfront",
        "eom": True,
        "modifier": "mf",
        "calendar": "syd",
        "payment_lag": 0,
        "currency": "aud",
        "convention": "act365f",
        "leg2_spread_compound_method": "none_simple",
        "leg2_fixing_method": "ibor(0)",
    },
    "aud_irs3_gt_3y": {
        "frequency": "s",
        "stub": "shortfront",
        "eom": True,
        "modifier": "mf",
        "calendar": "syd",
        "payment_lag": 0,
        "currency": "aud",
        "convention": "act365f",
        "leg2_frequency": "q",
        "leg2_spread_compound_method": "none_simple",
        "leg2_fixing_method": "ibor(0)",
    },
    "aud_irs": {
        "frequency": "a",
        "stub": "shortfront",
        "eom": True,
        "modifier": "mf",
        "calendar": "syd",
        "payment_lag": 2,
        "currency": "aud",
        "convention": "act365f",
        "leg2_spread_compound_method": "none_simple",
        "leg2_fixing_method": "rfr_payment_delay",
    },
    "eur_irs6": {
        "frequency": "a",
        "stub": "shortfront",
        "eom": False,
        "modifier": "mf",
        "calendar": "tgt",
        "payment_lag": 0,
        "currency": "eur",
        "convention": "30e360",
        "leg2_frequency": "s",
        "leg2_convention": "act360",
        "leg2_spread_compound_method": "none_simple",
        "leg2_fixing_method": "ibor(2)",
    },
    "eur_irs3": {
        "frequency": "a",
        "stub": "shortfront",
        "eom": False,
        "modifier": "mf",
        "calendar": "tgt",
        "payment_lag": 0,
        "currency": "eur",
        "convention": "30e360",
        "leg2_frequency": "q",
        "leg2_convention": "act360",
        "leg2_spread_compound_method": "none_simple",
        "leg2_fixing_method": "ibor(2)",
    },
    "eur_irs1": {
        "frequency": "a",
        "stub": "shortfront",
        "eom": False,
        "modifier": "mf",
        "calendar": "tgt",
        "payment_lag": 0,
        "currency": "eur",
        "convention": "30e360",
        "leg2_frequency": "m",
        "leg2_convention": "act360",
        "leg2_spread_compound_method": "none_simple",
        "leg2_fixing_method": "ibor(2)",
    },
    "sek_irs3": {
        "frequency": "a",
        "stub": "shortfront",
        "eom": False,
        "modifier": "mf",
        "calendar": "stk",
        "payment_lag": 0,
        "currency": "sek",
        "convention": "30e360",
        "leg2_frequency": "q",
        "leg2_convention": "act360",
        "leg2_spread_compound_method": "none_simple",
        "leg2_fixing_method": "ibor(2)",
    },
    "nok_irs3": {
        "frequency": "a",
        "stub": "shortfront",
        "eom": False,
        "modifier": "mf",
        "calendar": "osl",
        "payment_lag": 0,
        "currency": "nok",
        "convention": "30e360",
        "leg2_frequency": "q",
        "leg2_convention": "act360",
        "leg2_spread_compound_method": "none_simple",
        "leg2_fixing_method": "ibor(2)",
    },
    "nok_irs6": {
        "frequency": "a",
        "stub": "shortfront",
        "eom": False,
        "modifier": "mf",
        "calendar": "osl",
        "payment_lag": 0,
        "currency": "nok",
        "convention": "30e360",
        "leg2_frequency": "s",
        "leg2_convention": "act360",
        "leg2_spread_compound_method": "none_simple",
        "leg2_fixing_method": "ibor(2)",
    },
    "eurusd_xcs": {
        "frequency": "q",
        "stub": "shortfront",
        "eom": False,
        "modifier": "mf",
        "calendar": "tgt,nyc",
        "payment_lag": 2,
        "currency": "eur",
        "convention": "act360",
        "spread_compound_method": "none_simple",
        "fixing_method": "rfr_payment_delay",
        "payment_lag_exchange": 0,
        "fixed": False,
        "pair": "eurusd",
        "leg2_spread_compound_method": "none_simple",
        "leg2_fixing_method": "rfr_payment_delay",
        "leg2_fixed": False,
        "leg2_mtm": True,
    },
    "gbpusd_xcs": {
        "frequency": "q",
        "stub": "shortfront",
        "eom": False,
        "modifier": "mf",
        "calendar": "ldn,nyc",
        "payment_lag": 2,
        "currency": "gbp",
        "convention": "act365f",
        "spread_compound_method": "none_simple",
        "fixing_method": "rfr_payment_delay",
        "payment_lag_exchange": 0,
        "fixed": False,
        "pair": "gbpusd",
        "leg2_convention": "act360",
        "leg2_spread_compound_method": "none_simple",
        "leg2_fixing_method": "rfr_payment_delay",
        "leg2_fixed": False,
        "leg2_mtm": True,
    },
    "eurgbp_xcs": {
        "frequency": "q",
        "stub": "shortfront",
        "eom": False,
        "modifier": "mf",
        "calendar": "tgt,ldn",
        "payment_lag": 2,
        "currency": "eur",
        "convention": "act360",
        "spread_compound_method": "none_simple",
        "fixing_method": "rfr_payment_delay",
        "payment_lag_exchange": 0,
        "fixed": False,
        "pair": "eurgbp",
        "leg2_convention": "act365f",
        "leg2_spread_compound_method": "none_simple",
        "leg2_fixing_method": "rfr_payment_delay",
        "leg2_fixed": False,
        "leg2_mtm": True,
    },
    "gbpeur_xcs": {
        "frequency": "q",
        "stub": "shortfront",
        "eom": False,
        "modifier": "mf",
        "calendar": "tgt,ldn",
        "payment_lag": 2,
        "currency": "gbp",
        "convention": "act365f",
        "spread_compound_method": "none_simple",
        "fixing_method": "rfr_payment_delay",
        "payment_lag_exchange": 0,
        "fixed": False,
        "pair": "eurgbp",
        "leg2_convention": "act360",
        "leg2_spread_compound_method": "none_simple",
        "leg2_fixing_method": "rfr_payment_delay",
        "leg2_fixed": False,
        "leg2_mtm": True,
    },
    "jpyusd_xcs": {
        "frequency": "q",
        "stub": "shortfront",
        "eom": False,
        "modifier": "mf",
        "calendar": "nyc,tyo",
        "payment_lag": 2,
        "currency": "jpy",
        "convention": "act365f",
        "spread_compound_method": "none_simple",
        "fixing_method": "rfr_payment_delay",
        "payment_lag_exchange": 0,
        "fixed": False,
        "pair": "usdjpy",
        "leg2_convention": "act360",
        "leg2_spread_compound_method": "none_simple",
        "leg2_fixing_method": "rfr_payment_delay",
        "leg2_fixed": False,
        "leg2_mtm": True,
    },
    "audusd_xcs3": {
        "frequency": "q",
        "stub": "shortfront",
        "eom": False,
        "modifier": "mf",
        "calendar": "nyc,syd",
        "payment_lag": 2,
        "currency": "aud",
        "convention": "act365f",
        "spread_compound_method": "none_simple",
        "fixing_method": "ibor(0)",
        "payment_lag_exchange": 0,
        "fixed": False,
        "pair": "audusd",
        "leg2_convention": "act360",
        "leg2_spread_compound_method": "none_simple",
        "leg2_fixing_method": "rfr_payment_delay",
        "leg2_fixed": False,
        "leg2_mtm": True,
    },
    "audusd_xcs": {
        "frequency": "q",
        "stub": "shortfront",
        "eom": False,
        "modifier": "mf",
        "calendar": "nyc,syd",
        "payment_lag": 2,
        "currency": "aud",
        "convention": "act365f",
        "spread_compound_method": "none_simple",
        "fixing_method": "rfr_payment_delay",
        "payment_lag_exchange": 0,
        "fixed": False,
        "pair": "audusd",
        "leg2_convention": "act360",
        "leg2_spread_compound_method": "none_simple",
        "leg2_fixing_method": "rfr_payment_delay",
        "leg2_fixed": False,
        "leg2_mtm": True,
    },
    "nzdusd_xcs3": {
        "frequency": "q",
        "stub": "shortfront",
        "eom": False,
        "modifier": "mf",
        "calendar": "nyc,wlg",
        "payment_lag": 2,
        "currency": "nzd",
        "convention": "act365f",
        "spread_compound_method": "none_simple",
        "fixing_method": "ibor(0)",
        "payment_lag_exchange": 0,
        "fixed": False,
        "pair": "nzdusd",
        "leg2_convention": "act360",
        "leg2_spread_compound_method": "none_simple",
        "leg2_fixing_method": "rfr_payment_delay",
        "leg2_fixed": False,
        "leg2_mtm": True,
    },
    "nzdaud_xcs3": {
        "frequency": "q",
        "stub": "shortfront",
        "eom": False,
        "modifier": "mf",
        "calendar": "nyc,wlg,syd",
        "payment_lag": 2,
        "currency": "nzd",
        "convention": "act365f",
        "spread_compound_method": "none_simple",
        "fixing_method": "ibor(0)",
        "payment_lag_exchange": 0,
        "fixed": False,
        "pair": "audnzd",
        "leg2_convention": "act365f",
        "leg2_spread_compound_method": "none_simple",
        "leg2_fixing_method": "ibor(0)",
        "leg2_fixed": False,
        "leg2_mtm": True,
    },
    "eur_zcis": {
        "frequency": "a",
        "stub": "shortfront",
        "eom": False,
        "modifier": "mf",
        "calendar": "tgt",
        "payment_lag": 0,
        "currency": "eur",
        "convention": "1+",
        "leg2_index_method": "monthly",
        "leg2_index_lag": 3,
    },
    "gbp_zcis": {
        "frequency": "a",
        "stub": "shortfront",
        "eom": False,
        "modifier": "mf",
        "calendar": "ldn",
        "payment_lag": 0,
        "currency": "gbp",
        "convention": "1+",
        "leg2_index_method": "monthly",
        "leg2_index_lag": 2,
    },
    "usd_zcis": {
        "frequency": "a",
        "stub": "shortfront",
        "eom": False,
        "modifier": "mf",
        "calendar": "nyc",
        "payment_lag": 0,
        "currency": "usd",
        "convention": "1+",
        "leg2_index_method": "daily",
        "leg2_index_lag": 3,
    },
    "gbp_zcs": {
        "frequency": "a",
        "stub": "shortfront",
        "eom": True,
        "modifier": "mf",
        "calendar": "ldn",
        "payment_lag": 0,
        "currency": "gbp",
        "convention": "act365f",
        "leg2_spread_compound_method": "none_simple",
        "leg2_fixing_method": "rfr_payment_delay",
    },
    "sek_iirs": {
        "frequency": "a",
        "stub": "shortfront",
        "eom": False,
        "modifier": "none",
        "calendar": "stk",
        "payment_lag": 0,
        "currency": "sek",
        "convention": "actacticma",
        "index_method": "daily",
        "index_lag": 3,
        "leg2_frequency": "q",
        "leg2_convention": "act360",
        "leg2_spread_compound_method": "none_simple",
        "leg2_fixing_method": "ibor(2)",
    },
    "eur_sbs36": {
        "frequency": "q",
        "stub": "shortfront",
        "eom": False,
        "modifier": "mf",
        "calendar": "tgt",
        "payment_lag": 0,
        "currency": "eur",
        "convention": "act360",
        "spread_compound_method": "none_simple",
        "fixing_method": "ibor(2)",
        "leg2_frequency": "s",
        "leg2_spread_compound_method": "none_simple",
        "leg2_fixing_method": "ibor(2)",
    },
    "nok_sbs36": {
        "frequency": "q",
        "stub": "shortfront",
        "eom": False,
        "modifier": "mf",
        "calendar": "osl",
        "payment_lag": 0,
        "currency": "nok",
        "convention": "act360",
        "spread_compound_method": "none_simple",
        "fixing_method": "ibor(2)",
        "leg2_frequency": "s",
        "leg2_spread_compound_method": "none_simple",
        "leg2_fixing_method": "ibor(2)",
    },
    "aud_sbs36": {
        "frequency": "q",
        "stub": "shortfront",
        "eom": False,
        "modifier": "mf",
        "calendar": "syd",
        "payment_lag": 0,
        "currency": "aud",
        "convention": "act365f",
        "spread_compound_method": "none_simple",
        "fixing_method": "ibor(0)",
        "leg2_frequency": "s",
        "leg2_spread_compound_method": "none_simple",
        "leg2_fixing_method": "ibor(0)",
    },
    "aud_sbs31": {
        "frequency": "q",
        "stub": "shortfront",
        "eom": False,
        "modifier": "mf",
        "calendar": "syd",
        "payment_lag": 0,
        "currency": "aud",
        "convention": "act365f",
        "spread_compound_method": "none_simple",
        "fixing_method": "ibor(0)",
        "leg2_frequency": "m",
        "leg2_spread_compound_method": "none_simple",
        "leg2_fixing_method": "ibor(0)",
    },
    "nzd_sbs36": {
        "frequency": "q",
        "stub": "shortfront",
        "eom": False,
        "modifier": "mf",
        "calendar": "wlg",
        "payment_lag": 0,
        "currency": "nzd",
        "convention": "act365f",
        "spread_compound_method": "none_simple",
        "fixing_method": "ibor(0)",
        "leg2_frequency": "s",
        "leg2_spread_compound_method": "none_simple",
        "leg2_fixing_method": "ibor(0)",
    },
    "nzd_sbs31": {
        "frequency": "q",
        "stub": "shortfront",
        "eom": False,
        "modifier": "mf",
        "calendar": "wlg",
        "payment_lag": 0,
        "currency": "nzd",
        "convention": "act365f",
        "spread_compound_method": "none_simple",
        "fixing_method": "ibor(0)",
        "leg2_frequency": "m",
        "leg2_spread_compound_method": "none_simple",
        "leg2_fixing_method": "ibor(0)",
    },
    "us_gb": {
        "frequency": "s",
        "stub": "shortfront",
        "eom": True,
        "modifier": "none",
        "calendar": "nyc",
        "payment_lag": 0,
        "currency": "usd",
        "convention": "actacticma",
        "payment_lag_exchange": 0,
        "settle": 1,
        "ex_div": 1,
        "calc_mode": "us_gb",
    },
    "us_gbi": {
        "frequency": "s",
        "stub": "shortfront",
        "eom": True,
        "modifier": "none",
        "calendar": "nyc",
        "payment_lag": 0,
        "currency": "usd",
        "convention": "actacticma",
        "payment_lag_exchange": 0,
        "index_method": "daily",
        "index_lag": 3,
        "settle": 1,
        "ex_div": 1,
        "calc_mode": "us_gb",
    },
    "us_corp": {
        "frequency": "s",
        "stub": "shortfront",
        "eom": True,
        "modifier": "none",
        "calendar": "nyc",
        "payment_lag": 0,
        "currency": "usd",
        "convention": "30u360",
        "payment_lag_exchange": 0,
        "settle": 1,
        "ex_div": 1,
        "calc_mode": "us_corp",
    },
    "us_muni": {
        "frequency": "s",
        "stub": "shortfront",
        "eom": True,
        "modifier": "none",
        "calendar": "nyc",
        "payment_lag": 0,
        "currency": "usd",
        "convention": "30u360",
        "payment_lag_exchange": 0,
        "settle": 1,
        "ex_div": 1,
        "calc_mode": "us_muni",
    },
    "us_gb_tsy": {
        "frequency": "s",
        "stub": "shortfront",
        "eom": True,
        "modifier": "none",
        "calendar": "nyc",
        "payment_lag": 0,
        "currency": "usd",
        "convention": "actacticma",
        "payment_lag_exchange": 0,
        "settle": 1,
        "ex_div": 1,
        "calc_mode": "us_gb_tsy",
    },
    "uk_gb": {
        "frequency": "s",
        "stub": "longfront",
        "eom": False,
        "modifier": "none",
        "calendar": "ldn",
        "payment_lag": 0,
        "currency": "gbp",
        "convention": "actacticma",
        "payment_lag_exchange": 0,
        "settle": 1,
        "ex_div": 7,
        "calc_mode": "uk_gb",
    },
    "nz_gb": {
        "frequency": "s",
        "stub": "shortfront",
        "eom": False,
        "modifier": "none",
        "calendar": "wlg",
        "payment_lag": 0,
        "currency": "nzd",
        "convention": "actacticma",
        "payment_lag_exchange": 0,
        "settle": 1,
        "ex_div": 8,
        "calc_mode": "nz_gb",
    },
    "de_gb": {
        "frequency": "a",
        "stub": "longfront",
        "eom": False,
        "modifier": "none",
        "calendar": "tgt",
        "payment_lag": 0,
        "currency": "eur",
        "convention": "actacticma",
        "payment_lag_exchange": 0,
        "settle": 2,
        "ex_div": 1,
        "calc_mode": "de_gb",
    },
    "fr_gb": {
        "frequency": "a",
        "stub": "shortfront",
        "eom": False,
        "modifier": "none",
        "calendar": "tgt",
        "payment_lag": 0,
        "currency": "eur",
        "convention": "actacticma",
        "payment_lag_exchange": 0,
        "settle": 2,
        "ex_div": 1,
        "calc_mode": "fr_gb",
    },
    "nl_gb": {
        "frequency": "a",
        "stub": "shortfront",
        "eom": False,
        "modifier": "none",
        "calendar": "tgt",
        "payment_lag": 0,
        "currency": "eur",
        "convention": "actacticma",
        "payment_lag_exchange": 0,
        "settle": 2,
        "ex_div": 1,
        "calc_mode": "nl_gb",
    },
    "it_gb": {
        "frequency": "s",
        "stub": "shortfront",
        "eom": False,
        "modifier": "none",
        "calendar": "tgt",
        "payment_lag": 0,
        "currency": "eur",
        "convention": "actacticma",
        "payment_lag_exchange": 0,
        "settle": 2,
        "ex_div": 1,
        "calc_mode": "it_gb",
    },
    "ch_gb": {
        "frequency": "a",
        "stub": "shortfront",
        "eom": False,
        "modifier": "none",
        "calendar": "zur",
        "payment_lag": 0,
        "currency": "chf",
        "convention": "30e360",
        "payment_lag_exchange": 0,
        "settle": 1,
        "ex_div": 1,
        "calc_mode": "ch_gb",
    },
    "se_gb": {
        "frequency": "a",
        "stub": "shortfront",
        "eom": False,
        "modifier": "none",
        "calendar": "stk",
        "payment_lag": 0,
        "currency": "sek",
        "convention": "actacticma",
        "payment_lag_exchange": 0,
        "settle": 2,
        "ex_div": 5,
        "calc_mode": "se_gb",
    },
    "no_gb": {
        "frequency": "a",
        "stub": "shortfront",
        "eom": False,
        "modifier": "none",
        "calendar": "osl",
        "payment_lag": 0,
        "currency": "nok",
        "convention": "actacticma_stub365f",
        "payment_lag_exchange": 0,
        "settle": 1,
        "ex_div": 1,
        "calc_mode": "no_gb",
    },
    "ca_gb": {
        "frequency": "s",
        "stub": "shortfront",
        "eom": False,
        "modifier": "none",
        "calendar": "tro",
        "payment_lag": 0,
        "currency": "cad",
        "convention": "actacticma_stub365f",
        "payment_lag_exchange": 0,
        "settle": 1,
        "ex_div": 1,
        "calc_mode": "ca_gb",
    },
    "us_gbb": {
        "eom": True,
        "modifier": "none",
        "calendar": "nyc",
        "payment_lag": 0,
        "currency": "usd",
        "convention": "act360",
        "payment_lag_exchange": 0,
        "settle": 1,
        "ex_div": 0,
        "calc_mode": "us_gbb",
    },
    "se_gbb": {
        "eom": False,
        "modifier": "none",
        "calendar": "stk",
        "payment_lag": 0,
        "currency": "sek",
        "convention": "act360",
        "payment_lag_exchange": 0,
        "settle": 2,
        "ex_div": 0,
        "calc_mode": "se_gbb",
    },
    "no_gbb": {
        "eom": False,
        "modifier": "none",
        "calendar": "osl",
        "payment_lag": 0,
        "currency": "nok",
        "convention": "act365f",
        "payment_lag_exchange": 0,
        "settle": 2,
        "ex_div": 0,
        "calc_mode": "no_gbb",
    },
    "uk_gbb": {
        "eom": True,
        "modifier": "none",
        "calendar": "ldn",
        "payment_lag": 0,
        "currency": "gbp",
        "convention": "act365f",
        "payment_lag_exchange": 0,
        "settle": 1,
        "ex_div": 0,
        "calc_mode": "uk_gbb",
    },
    "uk_gbi": {
        "frequency": "s",
        "stub": "shortfront",
        "eom": False,
        "modifier": "none",
        "calendar": "ldn",
        "payment_lag": 0,
        "currency": "gbp",
        "convention": "actacticma",
        "payment_lag_exchange": 0,
        "index_method": "daily",
        "index_lag": 3,
        "settle": 1,
        "ex_div": 7,
        "calc_mode": "uk_gb",
    },
    "sek_fra3": {
        "termination": "3m",
        "frequency": "q",
        "eom": False,
        "modifier": "mf",
        "calendar": "stk",
        "payment_lag": 0,
        "currency": "sek",
        "convention": "act360",
        "leg2_spread_compound_method": "none_simple",
        "leg2_fixing_method": "ibor(2)",
    },
    "eur_fra3": {
        "termination": "3m",
        "frequency": "q",
        "eom": False,
        "modifier": "mf",
        "calendar": "tgt",
        "payment_lag": 0,
        "currency": "eur",
        "convention": "act360",
        "leg2_spread_compound_method": "none_simple",
        "leg2_fixing_method": "ibor(2)",
    },
    "eur_fra6": {
        "termination": "6m",
        "frequency": "s",
        "eom": False,
        "modifier": "mf",
        "calendar": "tgt",
        "payment_lag": 0,
        "currency": "eur",
        "convention": "act360",
        "leg2_spread_compound_method": "none_simple",
        "leg2_fixing_method": "ibor(2)",
    },
    "eur_fra1": {
        "termination": "1m",
        "frequency": "m",
        "eom": False,
        "modifier": "mf",
        "calendar": "tgt",
        "payment_lag": 0,
        "currency": "eur",
        "convention": "act360",
        "leg2_spread_compound_method": "none_simple",
        "leg2_fixing_method": "ibor(2)",
    },
    "nok_fra3": {
        "termination": "3m",
        "frequency": "q",
        "eom": False,
        "modifier": "mf",
        "calendar": "osl",
        "payment_lag": 0,
        "currency": "nok",
        "convention": "act360",
        "leg2_spread_compound_method": "none_simple",
        "leg2_fixing_method": "ibor(2)",
    },
    "nok_fra6": {
        "termination": "6m",
        "frequency": "s",
        "eom": False,
        "modifier": "mf",
        "calendar": "osl",
        "payment_lag": 0,
        "currency": "nok",
        "convention": "act360",
        "leg2_spread_compound_method": "none_simple",
        "leg2_fixing_method": "ibor(2)",
    },
    "usd_frn5": {
        "frequency": "q",
        "eom": False,
        "modifier": "mf",
        "calendar": "nyc",
        "payment_lag": 0,
        "currency": "usd",
        "convention": "act360",
        "spread_compound_method": "none_simple",
        "fixing_method": "rfr_observation_shift(5)",
        "settle": 1,
        "ex_div": 1,
    },
    "usd_stir": {
        "frequency": "q",
        "roll": "imm",
        "eom": False,
        "modifier": "mf",
        "calendar": "nyc",
        "payment_lag": 0,
        "currency": "usd",
        "convention": "actacticma",
        "nominal": 1000000.0,
        "leg2_spread_compound_method": "none_simple",
        "leg2_fixing_method": "rfr_payment_delay",
        "leg2_fixing_series": "usd_rfr",
    },
    "usd_stir1": {
        "frequency": "m",
        "roll": "som",
        "eom": False,
        "modifier": "mf",
        "calendar": "nyc",
        "payment_lag": 0,
        "currency": "usd",
        "convention": "actacticma",
        "nominal": 5000400.0,
        "leg2_spread_compound_method": "none_simple",
        "leg2_fixing_method": "rfr_payment_delay_avg",
        "leg2_fixing_series": "usd_rfr",
    },
    "eur_stir": {
        "frequency": "q",
        "roll": "imm",
        "eom": False,
        "modifier": "mf",
        "calendar": "tgt",
        "payment_lag": 0,
        "currency": "eur",
        "convention": "actacticma",
        "nominal": 1000000.0,
        "leg2_spread_compound_method": "none_simple",
        "leg2_fixing_method": "rfr_payment_delay",
        "leg2_fixing_series": "eur_rfr",
    },
    "eur_stir1": {
        "frequency": "m",
        "roll": "som",
        "eom": False,
        "modifier": "mf",
        "calendar": "tgt",
        "payment_lag": 0,
        "currency": "eur",
        "convention": "actacticma",
        "nominal": 3000000.0,
        "leg2_spread_compound_method": "none_simple",
        "leg2_fixing_method": "rfr_payment_delay_avg",
        "leg2_fixing_series": "eur_rfr",
    },
    "eur_stir3": {
        "frequency": "q",
        "roll": "imm",
        "eom": False,
        "modifier": "mf",
        "calendar": "tgt",
        "payment_lag": 0,
        "currency": "eur",
        "convention": "actacticma",
        "nominal": 1000000.0,
        "leg2_spread_compound_method": "none_simple",
        "leg2_fixing_method": "ibor(2)",
        "leg2_fixing_series": "eur_ibor",
    },
    "gbp_stir": {
        "frequency": "q",
        "roll": "imm",
        "eom": False,
        "modifier": "mf",
        "calendar": "ldn",
        "payment_lag": 0,
        "currency": "gbp",
        "convention": "actacticma",
        "nominal": 1000000.0,
        "leg2_spread_compound_method": "none_simple",
        "leg2_fixing_method": "rfr_payment_delay",
        "leg2_fixing_series": "gbp_rfr",
    },
    "uk_gb_2y": {
        "calendar": "ldn",
        "currency": "gbp",
        "calc_mode": "ice_gbp",
        "nominal": 100000.0,
        "coupon": 3.0,
    },
    "uk_gb_5y": {
        "calendar": "ldn",
        "currency": "gbp",
        "calc_mode": "ice_gbp",
        "nominal": 100000.0,
        "coupon": 4.0,
    },
    "uk_gb_10y": {
        "calendar": "ldn",
        "currency": "gbp",
        "calc_mode": "ice_gbp",
        "nominal": 100000.0,
        "coupon": 4.0,
    },
    "uk_gb_30y": {
        "calendar": "ldn",
        "currency": "gbp",
        "calc_mode": "ice_gbp",
        "nominal": 100000.0,
        "coupon": 4.0,
    },
    "us_gb_2y": {
        "calendar": "fed",
        "currency": "usd",
        "calc_mode": "ust_short",
        "nominal": 200000.0,
        "coupon": 6.0,
    },
    "us_gb_3y": {
        "calendar": "fed",
        "currency": "usd",
        "calc_mode": "ust_short",
        "nominal": 200000.0,
        "coupon": 6.0,
    },
    "us_gb_5y": {
        "calendar": "fed",
        "currency": "usd",
        "calc_mode": "ust_short",
        "nominal": 100000.0,
        "coupon": 6.0,
    },
    "us_gb_10y": {
        "calendar": "fed",
        "currency": "usd",
        "calc_mode": "ust_long",
        "nominal": 100000.0,
        "coupon": 6.0,
    },
    "us_gb_30y": {
        "calendar": "fed",
        "currency": "usd",
        "calc_mode": "ust_long",
        "nominal": 100000.0,
        "coupon": 6.0,
    },
    "de_gb_2y": {
        "calendar": "tgt",
        "currency": "eur",
        "calc_mode": "eurex_eur",
        "nominal": 100000.0,
        "coupon": 6.0,
    },
    "de_gb_5y": {
        "calendar": "tgt",
        "currency": "eur",
        "calc_mode": "eurex_eur",
        "nominal": 100000.0,
        "coupon": 6.0,
    },
    "de_gb_10y": {
        "calendar": "tgt",
        "currency": "eur",
        "calc_mode": "eurex_eur",
        "nominal": 100000.0,
        "coupon": 6.0,
    },
    "de_gb_30y": {
        "calendar": "tgt",
        "currency": "eur",
        "calc_mode": "eurex_eur",
        "nominal": 100000.0,
        "coupon": 4.0,
    },
    "fr_gb_5y": {
        "calendar": "tgt",
        "currency": "eur",
        "calc_mode": "eurex_eur",
        "nominal": 100000.0,
        "coupon": 6.0,
    },
    "fr_gb_10y": {
        "calendar": "tgt",
        "currency": "eur",
        "calc_mode": "eurex_eur",
        "nominal": 100000.0,
        "coupon": 6.0,
    },
    "sp_gb_10y": {
        "calendar": "tgt",
        "currency": "eur",
        "calc_mode": "eurex_eur",
        "nominal": 100000.0,
        "coupon": 6.0,
    },
    "ch_gb_10y": {
        "calendar": "zur",
        "currency": "chf",
        "calc_mode": "eurex_chf",
        "nominal": 100000.0,
        "coupon": 6.0,
    },
}

DEVELOPMENT = os.environ.get("RATESLIB_DEVELOPMENT", "True")
if DEVELOPMENT == "True":
    # DEVELOPMENT mode is used to load and create instrument specs from a CSV file.
    # This is loaded by default and slower to parse than directly creating a dict
    # So when packaging output the INSTRUMENT_SPEC dict and paste into the non-development
    # section.

    if version.parse(pd.__version__) < version.parse("3.0.0"):
        raise RuntimeError(
            "Development of instrument `spec` loading from CSV should be handled by pandas >= 3.0."
            "To avoid development mode set DEVELOPMENT=False."
        )

    path = "data/__instrument_spec.csv"
    abspath = os.path.dirname(os.path.abspath(__file__))
    target = os.path.join(abspath, path)
    df2 = pd.read_csv(target, header=[0, 1, 2, 3], index_col=[0])

    for column in df2.columns:
        df2[column] = df2[column].astype(column[3])  # type: ignore[call-overload]
    df2_legs = df2.loc[:, (slice(None), ["leg1", "leg2"])]

    INSTRUMENT_SPECS: dict[str, dict[str, Any]] = {}
    for spec in df2_legs.index:
        leg1 = df2_legs.loc[spec].dropna().droplevel([0, 3]).loc["leg1"].to_dict()
        try:
            leg2 = df2_legs.loc[spec].dropna().droplevel([0, 3]).loc["leg2"].to_dict()
        except KeyError:
            leg2 = {}
        INSTRUMENT_SPECS.update({spec: {**leg1, **{f"leg2_{k}": v for k, v in leg2.items()}}})

    # extra dtype conversion mappings for keys
    def _map_str_float_int(v: Any) -> Any:
        try:
            return int(float(v))
        except (ValueError, TypeError):
            return v

    _maps = {
        "roll": _map_str_float_int,
        "leg2_roll": _map_str_float_int,
    }

    for _, v in INSTRUMENT_SPECS.items():
        for k2, v2 in v.items():
            if k2 in _maps:
                v[k2] = _maps[k2](v2)
