# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Ubuntu Pytest

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.10", "3.11", "3.12", "3.13", "3.14" ]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Rust
      uses: actions-rust-lang/setup-rust-toolchain@v1

    - name: Set up uv
      uses: astral-sh/setup-uv@v5
      with:
        enable-cache: true
        python-version: ${{ matrix.python-version }}

    #    - name: Test with pytest and display Coverage
    #      env:
    #        RATESLIB_LICENCE: ${{ secrets.RATESLIB_LICENCE }}
    #      run: |
    #        uv run --group test coverage run -m --source=rateslib pytest
    #        uv run coverage report -m

    - name: Test with pytest
      env:
        RATESLIB_LICENCE: ${{ secrets.RATESLIB_LICENCE }}
      run: |
        uv run --group test pytest
